### ISSUE TITLE
Issue with host name having "-"

### ISSUE THREAD

**Issue by kesavkolla** [kaerus-component/urlparser#1]
If host name contains dash "-" then url parse is not working well.

Example:
urlparser.parse('http://user:pass@host-name.com:7219/_system')
{ host:
   { protocol: 'http',
     username: 'user',
     password: 'pass',
     hostname: 'host' },
  path: { base: '-name.com', name: '7219/_system' } }

**Comment by kaerus** [comment]
Oh, me bad, I'll write a test for it and adjust the regexp accordingly.
